"""create knowledge document chunks table

Revision ID: 631024580f8f
Revises: 3d03bb2d21b5
Create Date: 2026-09-06 21:57:23.331054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '631024580f8f'
down_revision: Union[str, Sequence[str], None] = '3d03bb2d21b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_document_chunks_document_id'), 'knowledge_document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_document_chunks_id'), 'knowledge_document_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_document_chunks_id'), table_name='knowledge_document_chunks')
    op.drop_index(op.f('ix_knowledge_document_chunks_document_id'), table_name='knowledge_document_chunks')
    op.drop_table('knowledge_document_chunks')
    # ### end Alembic commands ###
