"""add user_id to guests

Revision ID: c9c25b8e3a0d
Revises: 631024580f8f
Create Date: 2026-09-08 20:03:42.996503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c25b8e3a0d'
down_revision: Union[str, Sequence[str], None] = '631024580f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_guests_user_id'), 'guests', ['user_id'], unique=True)
    op.create_foreign_key(None, 'guests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guests', type_='foreignkey')
    op.drop_index(op.f('ix_guests_user_id'), table_name='guests')
    op.drop_column('guests', 'user_id')
    # ### end Alembic commands ###
