"""create service requests table

Revision ID: cab9871185dd
Revises: 24c816b1b6c7
Create Date: 2026-09-06 15:26:02.359804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab9871185dd'
down_revision: Union[str, Sequence[str], None] = '24c816b1b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_guest_id'), 'service_requests', ['guest_id'], unique=False)
    op.create_index(op.f('ix_service_requests_id'), 'service_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_requests_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_guest_id'), table_name='service_requests')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
